package com.minikasirpintarfree.app.utils

import android.content.Context
import android.graphics.Bitmap
import android.os.Environment
import com.itextpdf.io.image.ImageDataFactory
import com.itextpdf.kernel.colors.ColorConstants
import com.itextpdf.kernel.geom.PageSize
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Image
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Table
import com.itextpdf.layout.properties.HorizontalAlignment
import com.itextpdf.layout.properties.TextAlignment
import com.itextpdf.layout.properties.UnitValue
import com.minikasirpintarfree.app.data.model.Produk
import java.io.ByteArrayOutputStream
import java.io.File
import java.text.NumberFormat
import java.text.SimpleDateFormat
import java.util.*

object BarcodePdfGenerator {
    
    /**
     * Generate PDF dengan barcode label untuk print
     * @param context Application context
     * @param produk Produk data
     * @param barcodeBitmap Barcode bitmap image
     * @return File PDF atau null jika gagal
     */
    fun generateBarcodePdf(
        context: Context,
        produk: Produk,
        barcodeBitmap: Bitmap
    ): File? {
        return try {
            // Create PDF file
            val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
            val fileName = "Barcode_${produk.nama}_$timestamp.pdf"
            
            val pdfDir = File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), "MiniKasir")
            if (!pdfDir.exists()) {
                pdfDir.mkdirs()
            }
            
            val pdfFile = File(pdfDir, fileName)
            val writer = PdfWriter(pdfFile)
            val pdfDoc = PdfDocument(writer)
            
            // A6 size (105 x 148 mm) untuk label
            val document = Document(pdfDoc, PageSize(298f, 420f)) // A6 in points
            document.setMargins(20f, 20f, 20f, 20f)
            
            // Title
            val title = Paragraph("BARCODE PRODUK")
                .setFontSize(16f)
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(10f)
            document.add(title)
            
            // Barcode Image
            val stream = ByteArrayOutputStream()
            barcodeBitmap.compress(Bitmap.CompressFormat.PNG, 100, stream)
            val barcodeImage = Image(ImageDataFactory.create(stream.toByteArray()))
            barcodeImage.setHorizontalAlignment(HorizontalAlignment.CENTER)
            barcodeImage.setWidth(UnitValue.createPercentValue(80f))
            barcodeImage.setMarginBottom(10f)
            document.add(barcodeImage)
            
            // Barcode Number
            val barcodeNumber = Paragraph(produk.barcode ?: "")
                .setFontSize(12f)
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(15f)
            document.add(barcodeNumber)
            
            // Product Info Table
            val table = Table(UnitValue.createPercentArray(floatArrayOf(1f, 2f)))
            table.setWidth(UnitValue.createPercentValue(100f))
            
            // Nama Produk
            table.addCell(
                Paragraph("Nama:").setBold().setFontSize(10f)
            )
            table.addCell(
                Paragraph(produk.nama).setFontSize(10f)
            )
            
            // Kategori
            table.addCell(
                Paragraph("Kategori:").setBold().setFontSize(10f)
            )
            table.addCell(
                Paragraph(produk.kategori).setFontSize(10f)
            )
            
            // Harga
            val formatter = NumberFormat.getCurrencyInstance(Locale("id", "ID"))
            table.addCell(
                Paragraph("Harga:").setBold().setFontSize(10f)
            )
            table.addCell(
                Paragraph(formatter.format(produk.harga)).setFontSize(10f)
            )
            
            // Stok
            table.addCell(
                Paragraph("Stok:").setBold().setFontSize(10f)
            )
            table.addCell(
                Paragraph("${produk.stok} pcs").setFontSize(10f)
            )
            
            document.add(table)
            
            // Footer
            val footer = Paragraph("\nGenerated by Mini Kasir Pintar")
                .setFontSize(8f)
                .setTextAlignment(TextAlignment.CENTER)
                .setFontColor(ColorConstants.GRAY)
                .setMarginTop(15f)
            document.add(footer)
            
            // Close document
            document.close()
            
            pdfFile
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }
}